var fs = require('fs');
var readline = require('readline');
var $ = require('cheerio')
var moment = require('moment');
var google = require('googleapis');
var googleAuth = require('google-auth-library');
var request = require('request')
// var now = moment('2018-04-05'); // manually set to a date in April or October if needed
var now = moment();
var year = now.format('YYYY');
var month = now.format('MM');

// If modifying these scopes, delete your previously saved credentials
// at ~/.credentials/calendar-nodejs-quickstart.json
var SCOPES = ['https://www.googleapis.com/auth/calendar'];
var TOKEN_DIR = (process.env.HOME || process.env.HOMEPATH ||
    process.env.USERPROFILE) + '/.credentials/';
var TOKEN_PATH = TOKEN_DIR + 'calendar-nodejs-conference-scraper.json';

// Load client secrets from a local file.
fs.readFile('client_secret.json', function processClientSecrets(err, content) {
  if (err) {
    console.error('Error loading client secret file: ' + err);
    return;
  }
  // Authorize a client with the loaded credentials, then call the
  // Google Calendar API.
  authorize(JSON.parse(content), scrape);
});

/**
 * Create an OAuth2 client with the given credentials, and then execute the
 * given callback function.
 *
 * @param {Object} credentials The authorization client credentials.
 * @param {function} callback The callback to call with the authorized client.
 */
function authorize(credentials, callback) {
  var clientSecret = credentials.installed.client_secret;
  var clientId = credentials.installed.client_id;
  var redirectUrl = credentials.installed.redirect_uris[0];
  var auth = new googleAuth();
  var oauth2Client = new auth.OAuth2(clientId, clientSecret, redirectUrl);

  // Check if we have previously stored a token.
  fs.readFile(TOKEN_PATH, function(err, token) {
    if (err) {
      getNewToken(oauth2Client, callback);
    } else {
      oauth2Client.credentials = JSON.parse(token);
      callback(oauth2Client);
    }
  });
}

function scrape(auth) {
  request('https://www.lds.org/general-conference/' + year + '/' + month + '?lang=eng', function(err, response, body) {
      gotHTML(err,response, body, auth);
  });
}

function gotHTML(err, resp, html, auth) {
  if (err) return console.error(err)
  var $html = $.load(html)
  // get all img tags and loop over them
  talks = []
  $html('a.lumen-tile__link').map(function(i, link) {
    var title = $(link).find('.lumen-tile__title').text().replace(/\s\s+/g, ' ').trim();
    var author = $(link).find('.lumen-tile__content').text().replace(/\s\s+/g, ' ').trim();
    if (author == 'Video Presentation' ||
      title.indexOf('Sustaining of Church Officers') > -1 ||
      title.indexOf('Statistical Report') > -1 ||
      title.indexOf('Auditing Department') > -1
    ) {
      return;
    }
    talks.push(title + ' - ' + author);
  })

  // console.log("talks : ", talks); //debug!

  // Midnight, Sunday of the first week that we should put talks onto
  var startDate = moment(now, 'YYYY-MM-DD').isoWeekday('Sunday').hours(0).minutes(0).seconds(0);
  var firstDayOfNextAprilOrOctober = now.add(6, 'months').startOf('month') // date of next Conference
  var endDate = firstDayOfNextAprilOrOctober.day() % 6 === 0 ? firstDayOfNextAprilOrOctober : firstDayOfNextAprilOrOctober.add(1, 'week').day(0);

  var a = moment(startDate, 'YYYY-MM-DD');
  var b = moment(endDate, 'YYYY-MM-DD');
  var weeks = b.diff(a, 'weeks');

  var weeksWithTwoTalks = talks.length - weeks;

  var div = Math.floor(weeks/weeksWithTwoTalks);

  talkIndex = 0;
  for (var weekCount = 1; weekCount <= weeks; weekCount++) {
    var talk = talks[talkIndex++];
    if (typeof talk == 'undefined') {
      break;
    }
    var c = moment(startDate, 'YYYY-MM-DD').add(weekCount, 'weeks').add(2, 'days').add(7, 'hours'); // Tuesday!
    saveTalk(talk, c.toISOString(), c.add(15, 'minutes').toISOString(), auth);

    if ((weekCount % div) == 0) {
      var talk = talks[talkIndex++];
      var typeOf = typeof talk;
      if (typeof talk == 'undefined') {
        break;
      }
      var c = moment(startDate, 'YYYY-MM-DD').add(weekCount, 'weeks').add(4, 'days').add(7, 'hours'); // Thursday!
      saveTalk(talk, c.toISOString(), c.add(15, 'minutes').toISOString(), auth);
    }
  }
}

function saveTalk(talk, startDatetime, endDatetime, auth) {
  // console.log('saveTalk :', talk, startDatetime); // debug!
  var calendar = google.calendar('v3');
  calendar.events.insert({
      auth: auth,
      calendarId: "primary",
      resource: {
          start: {
            dateTime: startDatetime,
            timeZone: "America/Denver"
          },
          end: {
            dateTime: endDatetime,
            timeZone: "America/Denver"
          },
          summary: talk,
          description: "#ldsconf autogenerated event (" + year + "-" + month + ")"
      }
  }, function (err, success) {
      if (err) {
          console.error('Error adding %s at %s', talk, startDatetime, err);
      } else {
          console.log('Successfully added %s at %s', talk, startDatetime);
      }
  })
}

/**
 * Get and store new token after prompting for user authorization, and then
 * execute the given callback with the authorized OAuth2 client.
 *
 * @param {google.auth.OAuth2} oauth2Client The OAuth2 client to get token for.
 * @param {getEventsCallback} callback The callback to call with the authorized
 *     client.
 */
function getNewToken(oauth2Client, callback) {
  var authUrl = oauth2Client.generateAuthUrl({
    access_type: 'offline',
    scope: SCOPES
  });
  console.log('Authorize this app by visiting this url: ', authUrl);
  var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  rl.question('Enter the code from that page here: ', function(code) {
    rl.close();
    oauth2Client.getToken(code, function(err, token) {
      if (err) {
        console.log('Error while trying to retrieve access token', err);
        return;
      }
      oauth2Client.credentials = token;
      storeToken(token);
      callback(oauth2Client);
    });
  });
}

/**
 * Store token to disk be used in later program executions.
 *
 * @param {Object} token The token to store to disk.
 */
function storeToken(token) {
  try {
    fs.mkdirSync(TOKEN_DIR);
  } catch (err) {
    if (err.code != 'EEXIST') {
      throw err;
    }
  }
  fs.writeFile(TOKEN_PATH, JSON.stringify(token));
  console.log('Token stored to ' + TOKEN_PATH);
}
